### ISSUE TITLE
.ipynb 파일을 colab에서 실행하는 방법

### ISSUE THREAD

**Issue by changh95** [ai-robotics-kr/python_study#1]
@JungyeonLee6 님, 

메인 페이지의 readme.md에서 (#TODO) .ipynb 파일을 colab에서 로드해서 실행하는 방법을 적어주시면 좋을 것 같습니다 👍

**Comment by JungyeonLee6** [comment]
네넵!!

**Comment by changh95** [comment]
업데이트 되었습니다.
이슈 닫겠습니다.
